### ISSUE TITLE
Update data source and parsing from source

### ISSUE THREAD

**Issue by pramanikriju** [pramanikriju/covid-19-tracker-india#6]
Need to update the data source to get it to accurately populate it on the display

**Comment by saraogipraveen** [comment]
Hi @pramanikriju, right now I can see it is not even getting populated? do we need to change the source or to modify it?

**Comment by pramanikriju** [comment]
Modify it. The table still exists on the source page, just the processing should be updated

**Comment by saraogipraveen** [comment]
> Modify it. The table still exists on the source page, just the processing should be updated

Ok sure, I'll take a look, Please assign

**Comment by saraogipraveen** [comment]
@pramanikriju Also as per the new Oktoberfest update, kindly add hactoberfest topic to this repository to make this repo eligible for Hactoberfest 
Refer - https://twitter.com/hacktoberfest/status/1312221208667185153

**Comment by saraogipraveen** [comment]
> @pramanikriju Also as per the new Hacktoberfest update, kindly add hacktoberfest topic to this repository to make this repo eligible for Hacktoberfest
> Refer - https://twitter.com/hacktoberfest/status/1312221208667185153

![image](https://user-images.githubusercontent.com/16433473/95017802-28305e00-0679-11eb-8fe2-3d7e42ef3ed8.png)

**Comment by pramanikriju** [comment]
> @pramanikriju Also as per the new Hacktoberfest update, kindly add hacktoberfest topic to this repository to make this repo eligible for Hacktoberfest
> Refer - https://twitter.com/hacktoberfest/status/1312221208667185153

Can you confirm if it's eligible now?

**Comment by saraogipraveen** [comment]
> > @pramanikriju Also as per the new Hacktoberfest update, kindly add hacktoberfest topic to this repository to make this repo eligible for Hacktoberfest
> > Refer - https://twitter.com/hacktoberfest/status/1312221208667185153
> 
> Can you confirm if it's eligible now?

Yeah, it is. Thanks
