### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by thareshjose** [pramanikriju/covid-19-tracker-india#8]
Call to https://www.mohfw.gov.in/data/datanew.json is blocked by the CORS policy.

![image](https://user-images.githubusercontent.com/29145772/95020822-1e175b00-068b-11eb-8c02-652e5cf2e40e.png)

**Comment by pramanikriju** [comment]
Feel free to send a pull request by adding the required headers

**Comment by saraogipraveen** [comment]
Please close this issue if it's completed, as it is appearing in issuehub.io for contributors. Thanks
